map = global.enemymap 
sprite_index = map[? "Sprite"];
name = map[? "Name"];
hp = map[? "HP"] ;
spd = map[? "Speed"];
spawncost = map[? "Cost"];
spawnarea = map[? "Spawn Area"];
atkcooldown = map[? "Attack Cooldown"];
movetimer = map[? "Move Timer"]